const MovieDB = [
    {
        name: 'No Exit',
        poster_link: 'https://img1.hotstarext.com/image/upload/f_auto,t_hcdl/sources/r1/cms/prod/4075/1194075-h-58be4f64d4bb',
        background_img: 'https://img1.hotstarext.com/image/upload/f_auto,t_hcdl/sources/r1/cms/prod/4075/1194075-h-58be4f64d4bb',
        description: 'Stranded at an isolated highway rest stop in the mountains during a blizzard, a college student discovers a kidnapped child hidden in a car belonging to one of the people inside the building, which sets her on a terrifying life-or-death struggle to discover who among them is the kidnapper',
        trailer_link: 'https://youtu.be/GFvupyiNEz0',
        Id: '1',
    },
    {
        name: 'Restless',
        poster_link: 'https://m.media-amazon.com/images/M/MV5BMGMwYTRmMTMtODIyZS00NDJmLWE3M2ItNmJlMDUyNGRiMGEyXkEyXkFqcGdeQXVyMzcyNjQwODE@._V1_.jpg',
        background_img: 'https://https://m.media-amazon.com/images/M/MV5BMGMwYTRmMTMtODIyZS00NDJmLWE3M2ItNmJlMDUyNGRiMGEyXkEyXkFqcGdeQXVyMzcyNjQwODE@._V1_.jpg',
        description: "After going to extremes to cover up an accident, a corrupt cop's life spirals out of control when he starts receiving threats from a mysterious witness",
        trailer_link: 'https://youtu.be/L8tCoWmooRE',
        Id: '2',
    },
    {
        name: 'West Side Story',
        poster_link: 'https://lumiere-a.akamaihd.net/v1/images/p_westsidestory_22378_c99a2243.jpeg',
        background_img: 'https://lumiere-a.akamaihd.net/v1/images/p_westsidestory_22378_c99a2243.jpeg',
        description: 'A remake of the 1961 film about two youngsters from rival New York City gangs fall in love, but tensions between their respective friends build toward tragedy',
        trailer_link: 'https://youtu.be/snf7Pdn3Giw',
        Id: '3',
    },
    {
        name: 'Spider-Man: No Way Home',
        poster_link: 'https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UX1000_.jpg',
        background_img: 'https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UX1000_.jpg',
        description: 'Spider-Man: No Way Home is a 2021 American superhero film based on the Marvel Comics character Spider-Man, co-produced by Columbia Pictures and Marvel Studios and distributed by Sony Pictures Releasing',
        trailer_link: 'https://youtu.be/UV2ZWTSHjSs',
        Id: '4',
    },
    {
        name: "The King's Man",
        poster_link: 'https://lumiere-a.akamaihd.net/v1/images/p_thekingsman_22436_98192ba9.jpeg',
        background_img: 'https://lumiere-a.akamaihd.net/v1/images/p_thekingsman_22436_98192ba9.jpeg',
        description: "As a collection of history's worst tyrants and criminal masterminds gather to plot a war to wipe out millions, one man must race against time to stop them",
        trailer_link: 'https://youtu.be/MGoCwNHE4ys',
        Id: '5',
    },
    {
        name: 'Project Gemini',
        poster_link: 'https://m.media-amazon.com/images/M/MV5BZWFlMTMyZjctNTcyYi00ODM2LWE1NDYtZWMyODI0MTNkMDc0XkEyXkFqcGdeQXVyNjMzNjY2NjQ@._V1_.jpg',
        background_img: 'https://m.media-amazon.com/images/M/MV5BZWFlMTMyZjctNTcyYi00ODM2LWE1NDYtZWMyODI0MTNkMDc0XkEyXkFqcGdeQXVyNjMzNjY2NjQ@._V1_.jpg',
        description: 'Astrophysicists pick up a mysterious signal coming from outer space. An expedition sets out to visit this planet to find and inspect the source of the signal',
        trailer_link: 'https://youtu.be/Gi4Pobu1PWw',
        Id: '6',
    },
    {
        name: 'Scream',
        poster_link: 'https://upload.wikimedia.org/wikipedia/en/2/24/Scream2022film.jpeg',
        background_img: 'https://upload.wikimedia.org/wikipedia/en/2/24/Scream2022film.jpeg',
        description: "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town's deadly past",
        trailer_link: 'https://youtu.be/VYOLMjUXtl4',
        Id: '7',
    },
    {
        name: 'The 355',
        poster_link: 'https://m.media-amazon.com/images/M/MV5BNzk4MDZhNTctMDA3OC00ODdkLWIyOWYtN2M0MzA3MDY5NDk1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg',
        background_img: 'https://m.media-amazon.com/images/M/MV5BNzk4MDZhNTctMDA3OC00ODdkLWIyOWYtN2M0MzA3MDY5NDk1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg',
        description: 'A group of top female agents from government agencies around the globe try to stop an organization from acquiring a deadly weapon to send the world into chaos',
        trailer_link: 'https://youtu.be/MFVmUCB10aY',
        Id: '8',
    },
    {
        name: 'Big Gold Brick',
        poster_link: 'https://m.media-amazon.com/images/M/MV5BN2YyN2UzZjEtODExNy00MjJkLWJmZGYtYmM2OTY3ZDM1MzI4XkEyXkFqcGdeQXVyMjE4NzUxNDA@._V1_.jpg',
        background_img: 'https://m.media-amazon.com/images/M/MV5BN2YyN2UzZjEtODExNy00MjJkLWJmZGYtYmM2OTY3ZDM1MzI4XkEyXkFqcGdeQXVyMjE4NzUxNDA@._V1_.jpg',
        description: 'Recounts the story of fledgling writer Samuel Liston and his experiences with Floyd Deveraux, the enigmatic, middle-aged father of two who enlists Samuel to write his biography',
        trailer_link: 'https://youtu.be/uDoQ2qzO8Rw',
        Id: '9',
    },
    {
        name: 'Uncharted',
        poster_link: 'https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_.jpg',
        background_img: 'https://https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_.jpg',
        description: "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
        trailer_link: 'https://youtu.be/4wCH1K-ckZw',
        Id: '10',
    },
    {
        name: 'Desperate Riders',
        poster_link: 'https://m.media-amazon.com/images/M/MV5BZWUwOTAyZWQtN2M4Mi00NDAyLTg0MTUtZTM5ZTNhNWFiZTE0XkEyXkFqcGdeQXVyOTg4MDYyNw@@._V1_FMjpg_UX1000_.jpg',
        background_img: 'https://m.media-amazon.com/images/M/MV5BZWUwOTAyZWQtN2M4Mi00NDAyLTg0MTUtZTM5ZTNhNWFiZTE0XkEyXkFqcGdeQXVyOTg4MDYyNw@@._V1_FMjpg_UX1000_.jpg',
        description: "After Kansas Red rescues young Billy from a card-game shootout, the boy asks Red for help protecting his family from the outlaw Thorn, whos's just kidnapped Billy's mother, Carol. As Red and Billy ride off to rescue Carol, they run into beautiful, tough-as-nails Leslie, who’s managed to escape Thorn’s men. The three race to stop Thorn’s wedding to Carol with guns a-blazing - but does she want to be rescued?",
        trailer_link: 'https://youtu.be/AAwn9GqBiSY',
        Id: '11',
    },
    {
        name: 'The Matrix Resurrections',
        poster_link: 'https://www.whatisthematrix.com/assetsNew/images/banner_img_mobile.jpg',
        background_img: 'https://www.whatisthematrix.com/assetsNew/images/banner_img_mobile.jpg',
        description: 'The fourth installment in The Matrix franchise.',
        trailer_link: 'https://youtu.be/GlDr6aKBtFg',
        Id: '12',
    },
    {
        name: 'Eternals',
        poster_link: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/eternals_lob_crd_06.jpg',
        background_img: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/eternals_lob_crd_06.jpg',
        description: "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.",
        trailer_link: 'https://youtu.be/0WVDKZJkGlY',
        Id: '13',
    },
    {
        name: 'Ghostbusters: Afterlife',
        poster_link: 'https://m.media-amazon.com/images/M/MV5BMGY2NjUwODEtMGM5OS00MzhkLWEzYTUtYjkwMjFmNjhiN2FmXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_FMjpg_UX1000_.jpg',
        background_img: 'https://m.media-amazon.com/images/M/MV5BMGY2NjUwODEtMGM5OS00MzhkLWEzYTUtYjkwMjFmNjhiN2FmXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_FMjpg_UX1000_.jpg',
        description: 'When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.',
        trailer_link: 'https://youtu.be/lnKmAVLC3jU',
        Id: '14',
    },
    {
        name: 'House of Gucci',
        poster_link: 'https://upload.wikimedia.org/wikipedia/en/f/fe/House.of.Gucci.film.jpeg',
        background_img: 'https://upload.wikimedia.org/wikipedia/en/f/fe/House.of.Gucci.film.jpeg',
        description: 'The true story of how Patrizia Reggiani plotted to kill her husband Maurizio Gucci, the grandson of renowned fashion designer Guccio Gucci',
        trailer_link: 'https://youtu.be/yCNn1Q4_vys',
        Id: '15',
    }
]

export default MovieDB;